import { html } from "lit";
import { MDComponent } from "../../material/component/component.js";

class DemoNavigationBar extends MDComponent {
    render() {
        /* prettier-ignore */
        return html`
            <md-layout-border >
                <md-layout-border-item region="center">
                    <md-layout>
                        <md-layout-header>header</md-layout-header>
                        <md-layout-body style="padding:24px;">
                            
                            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptate aliquid harum ipsam facere esse eveniet accusantium, quos fugiat, repellat deleniti molestiae illum! Quisquam fugiat quos adipisci. Earum incidunt totam modi.</p>
                            <p>Eius, facere. Voluptatibus dolorum necessitatibus praesentium pariatur vero, ad, debitis dolor porro dolores quam similique, quae eius architecto expedita natus odio labore ducimus in aperiam sit nesciunt! Harum, assumenda neque!</p>
                            <p>Aliquam eligendi provident nulla delectus. Iure doloremque hic aperiam suscipit rem, consequuntur earum, quod est aliquid porro in nulla? A veniam culpa mollitia consequatur doloremque eius excepturi impedit commodi architecto.</p>
                            <p>Atque ea voluptas exercitationem quam placeat, sapiente impedit at, repudiandae voluptatum ex officiis natus nostrum! Voluptatibus accusamus quos molestiae eaque labore placeat, blanditiis quidem incidunt voluptatem illum ex eum a.</p>
                            <p>Commodi itaque sapiente fugit perspiciatis, odit qui. Nostrum dolor possimus vel porro ad voluptatibus earum blanditiis numquam maxime dolorem quod consequatur nemo deleniti non impedit, omnis odio voluptate expedita beatae?</p>
                            <p>Illo consequatur, sapiente ex facere voluptatum, suscipit aliquam laborum in hic ullam saepe odio voluptates, quas fuga necessitatibus explicabo soluta fugiat maiores nobis doloribus eveniet a non dolor! Quas, sunt.</p>
                            <p>Unde perspiciatis explicabo velit placeat, error nihil vero in alias obcaecati et, aliquam iure. Suscipit nobis voluptas cumque nam officiis, a et ipsa, nulla, excepturi quis exercitationem officia illo distinctio?</p>
                            <p>Quas tempora officia in ipsam unde ipsum cumque ratione. Minima aspernatur aperiam maiores vel tempora libero molestiae repudiandae recusandae autem quisquam sequi doloremque odit quam voluptatibus, commodi numquam similique provident.</p>
                            <p>Voluptatum soluta voluptatem cumque excepturi alias maiores quos nostrum quis placeat suscipit debitis veniam iure incidunt saepe, optio aut repellat est? Corporis ducimus beatae illum fuga perferendis similique et ullam?</p>
                            <p>Saepe inventore sunt, nulla hic doloribus perferendis omnis, assumenda quis accusantium architecto nihil vero aliquid eos officiis laudantium! Magnam, quam? Optio quod, illum rerum pariatur quaerat praesentium laborum saepe! Quasi.</p>
                            <p>Consequatur soluta enim cum quo aliquam veritatis culpa cupiditate dignissimos iusto dolorum est itaque nihil, explicabo deleniti debitis, impedit, incidunt magni fugit tempore officiis. Distinctio laboriosam aut sunt et quas.</p>
                            <p>Reiciendis libero nostrum incidunt qui, cumque nisi hic vitae iusto at maxime fuga explicabo necessitatibus corporis. Nostrum repellendus, vel quisquam ducimus ad enim neque repudiandae nihil excepturi amet? Voluptatum, quo.</p>
                            <p>Earum dolorem ad nemo quae expedita, maxime architecto quidem quis amet ea dignissimos itaque consectetur nisi adipisci suscipit vitae facilis recusandae exercitationem fuga assumenda at ipsum! Voluptates quia quidem atque.</p>
                            <p>Recusandae totam obcaecati ea excepturi corporis autem corrupti ipsa minima omnis necessitatibus vero magni nemo, optio asperiores nostrum consequatur libero voluptate consequuntur fugit explicabo id, eligendi pariatur? Voluptatem, libero! Voluptate.</p>
                            <p>Corporis quibusdam in dolorum praesentium consequatur aspernatur modi quae dolore consequuntur porro a libero debitis, amet deleniti voluptatibus, laboriosam iste natus ipsum. Aliquam repellendus vel corrupti dolor quis ipsa doloremque!</p>
                            <p>Natus suscipit eum doloribus, atque a quis saepe similique? Deserunt eum numquam, nulla explicabo modi, nobis assumenda voluptate porro temporibus unde quod fugiat repudiandae rem iure libero magnam molestiae tempora.</p>
                            <p>Ab ipsum iusto repellendus, laudantium cum cumque. Perspiciatis nobis incidunt magnam molestiae sapiente natus harum neque, aliquam totam ad ea? Earum sequi temporibus nihil natus obcaecati perferendis esse sunt repudiandae.</p>
                            <p>Illum dolor quas quia iusto suscipit aut laboriosam iure ea nisi, distinctio magni eaque quaerat perferendis quae ut vel praesentium expedita facere? Deleniti sed esse perspiciatis. Illo nobis doloremque atque!</p>
                            <p>Enim sint esse sapiente facilis, veniam quos in. Vel, natus odit. Harum, minus, aut non repudiandae maxime, aliquam nulla consequuntur accusamus laborum repellendus nobis iure beatae velit voluptate saepe amet.</p>
                            <p>Rerum iusto modi, eveniet placeat rem sequi accusamus ratione! Voluptate eum, tenetur perspiciatis possimus ratione, doloribus quae harum ab cumque, fuga corporis ipsa quia repudiandae nihil laudantium itaque. Quas, error!</p>
                            <p>Nemo quisquam dignissimos libero nulla eos odio similique odit necessitatibus veritatis amet, facilis corrupti iure maiores aperiam et obcaecati repellat temporibus. Repellat dolores earum, laudantium illum maiores similique labore explicabo.</p>
                            <p>Hic non a labore aperiam harum incidunt impedit deleniti minus corrupti deserunt, perspiciatis officia explicabo optio temporibus recusandae est quaerat alias ad quia inventore laborum quidem similique dolorem consequuntur. Ipsam?</p>
                            <p>Illum laborum vero eveniet! Perferendis consequuntur non odit et autem, hic quaerat recusandae sed dignissimos cumque maxime. Soluta quae aperiam dicta laborum, voluptas laudantium architecto molestias repellendus tenetur voluptates sapiente!</p>
                            <p>Veniam eaque minus delectus neque voluptatibus nulla libero repudiandae ipsum soluta perferendis! Molestiae aliquid voluptatum neque totam recusandae, alias repudiandae repellendus magni! Nam eius consequatur iure deleniti, a adipisci aspernatur?</p>
                            <p>Unde, eius, repellendus cumque aut ipsum, reprehenderit officiis cupiditate ipsa voluptatem aliquid non blanditiis saepe iste. Odio amet expedita labore eaque aperiam tempore, incidunt ad, corrupti, officiis inventore voluptas quae!</p>
                            <p>Asperiores, inventore quia. Sint blanditiis eos facilis, quos maxime error! Illo, et, hic ex suscipit recusandae maiores praesentium ducimus quam vel ipsa aut blanditiis minus numquam quis dolore voluptatem debitis?</p>
                            <p>Sapiente illum soluta ipsum veniam quod, doloremque vel aliquid recusandae voluptates nemo fuga illo obcaecati, adipisci, iure maxime quae. Quis, cumque. Odio eius tempore accusantium quia quis eos! Alias, iste.</p>
                            <p>Suscipit quasi deleniti, recusandae quae eius eos ut expedita sapiente quam ratione animi earum tempore reiciendis autem inventore ipsa itaque quibusdam excepturi labore. Quia laudantium magnam debitis perferendis iusto facere.</p>
                            <p>Facere, ea. Consequatur fugit a perferendis, placeat fuga nesciunt minus voluptatum totam provident nobis optio maiores commodi alias temporibus iste, et deleniti, neque amet. Facere, repudiandae sequi. Beatae, ab illum!</p>
                            <p>Reprehenderit, maxime. Ullam est distinctio minus, ipsum perspiciatis, consequatur porro temporibus neque eos debitis, id non expedita quae delectus voluptas sit rem. Aspernatur excepturi repellendus dicta pariatur quibusdam? Ipsa, dicta!</p>
                            <p>Minus voluptate deserunt numquam vel ut nam. Sapiente, unde ab possimus modi, optio recusandae provident aperiam nulla fuga ratione suscipit necessitatibus nisi iure amet officiis tempora vitae, eaque tenetur? In.</p>
                            <p>Accusantium, inventore. Autem quia, a culpa alias itaque, et, nesciunt reprehenderit nobis quos aliquam dolores provident corrupti! Voluptatem harum dicta facilis error nihil ratione distinctio quod laborum cumque? Aliquid, magni?</p>
                            <p>Ea, odit eum aliquid eaque alias molestiae mollitia error dolores perferendis ipsam rerum dolorem! Et assumenda qui, dolorem facilis minus ut similique minima. Deserunt iure suscipit mollitia ex a adipisci!</p>
                            <p>Fugiat aperiam fuga est consectetur, sequi cupiditate explicabo iusto nam voluptate nihil sed eius atque consequuntur suscipit minus ipsa necessitatibus esse velit optio quam vitae vero molestiae tenetur ipsam. Aut?</p>
                            <p>Blanditiis quo rem itaque ea pariatur impedit quae, minus molestiae. Nulla quos laboriosam iure laudantium ea impedit quo. Maxime libero, atque voluptatem accusamus ad quae voluptate? Cum necessitatibus molestias reprehenderit.</p>
                            <p>Repellat soluta provident quibusdam maxime ad. Id animi eaque perferendis in quam molestiae voluptatibus necessitatibus corporis vitae mollitia, aspernatur ab facilis ad sunt rerum officiis facere odio ratione sequi numquam?</p>
                            <p>Aliquid, ut ex incidunt minus esse commodi omnis numquam impedit dignissimos beatae repellendus tempore soluta reprehenderit aspernatur dolorum corporis ratione assumenda ipsa hic pariatur facere praesentium! Dolorem alias assumenda est?</p>
                            <p>Fuga voluptates maxime numquam provident officia perferendis et vitae illo. Vel doloremque repudiandae, facere, ut aut tempora atque incidunt molestiae quasi explicabo quisquam impedit labore dolorum ducimus cum exercitationem rem.</p>
                            <p>Consequuntur assumenda impedit voluptatibus itaque, a fugit minus quae accusantium quia! Eos necessitatibus ipsum molestiae consequuntur culpa! Enim inventore maxime ratione, assumenda earum aliquid praesentium hic? Et labore eum ut.</p>
                            <p>Deserunt adipisci, reiciendis iusto hic tempore nesciunt, neque, nostrum sed quod fugiat quidem deleniti error quo excepturi voluptatibus magnam atque iure minima! Sapiente laboriosam quis molestiae totam vel odit distinctio.</p>
                            <p>Omnis corrupti vitae, illum aut voluptas, laboriosam, veritatis soluta consectetur quas cum voluptatem itaque doloribus tempore dignissimos minima facilis quae dicta provident perspiciatis corporis. Nesciunt minima fugit harum inventore doloremque?</p>
                            <p>Ea, amet voluptate ut unde fugit velit soluta maxime est praesentium nostrum. Voluptates ea asperiores ipsum eaque ab dolores laudantium debitis nulla expedita doloribus! Est similique at perferendis id ut?</p>
                            <p>Ea reprehenderit totam assumenda vitae! Nostrum soluta laudantium, nam distinctio, veniam impedit repudiandae nulla possimus dignissimos quaerat quam atque corrupti consequuntur veritatis quidem, mollitia excepturi alias error dolorum obcaecati dolor.</p>
                            <p>Praesentium blanditiis quidem eius vero! Autem, odit adipisci a quia cum sit corporis. Veritatis adipisci aspernatur, voluptatibus quis optio sequi quas expedita magnam sit impedit! At blanditiis sapiente maxime. Sequi.</p>
                            <p>Molestias repudiandae quo tenetur quaerat aperiam. Officiis magnam mollitia modi sapiente repellat perferendis inventore illum iusto cum hic nihil architecto, incidunt est eveniet ab iste exercitationem rerum tenetur. Maxime, perspiciatis?</p>
                            <p>Ullam facere, ipsa alias at esse, temporibus officiis magni dignissimos deserunt quam omnis qui sit nam? Suscipit exercitationem reiciendis laborum at enim aliquid. Ab amet qui, fugiat blanditiis nostrum illum.</p>
                            <p>Sint cum enim, non architecto minus ad asperiores accusamus cumque saepe modi maiores dolorem veniam provident molestiae, doloremque ab dolorum corporis quia nulla molestias nemo esse! Hic quis exercitationem nemo.</p>
                            <p>Aliquid autem esse fuga tempore, numquam, ipsa quaerat sint ullam porro impedit recusandae? Tempore, nam facilis! Maxime saepe perspiciatis pariatur dicta architecto ea in, rem voluptates? Consequatur voluptas doloribus in?</p>
                            <p>Accusamus nostrum velit porro vero eum maxime eligendi esse totam harum sint doloribus fuga magni deserunt, alias quibusdam reiciendis temporibus obcaecati, excepturi ratione dolores id. Esse delectus expedita vero nisi!</p>
                            <p>Praesentium veniam amet odit inventore non cumque earum voluptas tempore est harum fugit exercitationem porro enim sit veritatis ab officiis quae, quia aspernatur iusto. Iusto ex libero eaque ullam sunt!</p>
                            <p>Dolore illo optio corporis atque quae numquam beatae saepe excepturi, ducimus nulla. Suscipit eos qui eligendi voluptatibus dicta quia quis, officia asperiores deleniti, veritatis rem quidem. Aliquid natus tempora exercitationem?</p>
                            <p>Nemo nulla tempora cupiditate quas aut ut, accusamus nam ratione delectus aspernatur consequatur, officia quidem ducimus commodi consequuntur illum soluta. Praesentium minus quia autem. Magni odio ipsa neque omnis id.</p>
                            <p>Odio dolor fugiat iusto numquam natus perferendis vitae quod eveniet possimus aperiam molestiae at nostrum rerum quidem quis optio consectetur sed dolorem, error aliquam commodi tempora tenetur beatae sapiente? Cumque.</p>
                            <p>Aperiam, labore. Distinctio voluptas harum ea ut molestiae rem ipsam excepturi aperiam consequatur tempore? Laborum tempora eius autem cumque. Error molestias atque quidem. Expedita sint autem ipsa adipisci magni iste.</p>
                            <p>Provident consectetur illo odit deserunt repellendus nobis, veniam ut ea ipsum cupiditate doloremque labore corporis in excepturi architecto eum voluptatem placeat omnis quis magnam ex vel! Dolorum repellat quaerat optio.</p>
                            <p>Velit natus maxime sit sequi facere, at aperiam, magni corrupti eius beatae consequatur dolorem fugit provident voluptas non quibusdam laudantium laborum nam aliquam dicta. Iure voluptatem labore impedit nobis. Laboriosam!</p>
                            <p>Dolor incidunt doloribus vel dolorum placeat libero, sit iste ad rem nam illum vero iure quaerat at, eius explicabo tempora nostrum corrupti. A dicta labore error! Eaque quaerat similique nemo!</p>
                            <p>Vel fugiat aliquam nulla alias delectus nisi debitis aspernatur ab nobis repudiandae quasi impedit, recusandae incidunt libero accusantium eligendi deleniti qui iste aperiam sit consectetur maiores dolor vero! Excepturi, doloribus.</p>
                            <p>Quod ut provident atque, possimus a totam architecto explicabo in accusamus aut, consequatur quam officiis quia vel sit quibusdam unde, maxime adipisci saepe quas molestiae asperiores reiciendis. Amet, laborum hic.</p>
                            <p>Sint quos pariatur reprehenderit dolor repellendus expedita eos dignissimos nobis, vel similique magni nulla atque officia odit. Provident voluptas magni dolor, natus nostrum placeat vitae ipsum beatae, fuga sint maiores?</p>
                            <p>Aliquid necessitatibus asperiores cum voluptate reiciendis maxime voluptates, amet ipsa hic. Expedita dolor voluptatibus laboriosam dolorum itaque? Libero inventore pariatur praesentium eum distinctio dolore aspernatur animi odit nisi, rem nostrum.</p>
                            <p>Itaque quisquam sed, ex velit deserunt deleniti harum fugiat neque minima voluptas quidem iusto repellendus, voluptatem aliquid aut vero recusandae cumque consequatur repellat officia. Quasi, incidunt necessitatibus? Repudiandae, alias pariatur?</p>
                            <p>Repellendus tempora vel impedit, corporis molestias tempore, voluptatum alias quibusdam magnam cumque modi et aut quia maiores nam. Error voluptas in vero provident ipsam, aperiam aliquam est distinctio numquam minima.</p>
                            <p>Quidem deserunt explicabo, excepturi voluptate deleniti facilis atque in natus expedita, ea tempore! Dolore natus iure voluptas quisquam saepe, error, deleniti sint ea fuga in culpa illo, sit asperiores! Optio.</p>
                            <p>Eos necessitatibus numquam laborum officia autem fugit praesentium beatae, sit incidunt cum blanditiis odit voluptate doloremque error expedita provident illum minus esse. Minus animi accusantium necessitatibus voluptates nam nostrum. Vero?</p>
                            <p>Iste placeat velit eos, facilis blanditiis suscipit vitae quaerat maiores dicta beatae sequi reiciendis cupiditate quam labore, ipsum ad iure possimus veritatis. At, ut beatae commodi soluta sequi cum eum!</p>
                            <p>Iste, laudantium, vero ratione fugiat culpa cum voluptatum id cumque quia aperiam, totam assumenda earum laboriosam officiis optio eos officia! Repellendus obcaecati inventore repellat nesciunt quidem, eaque labore dolore possimus?</p>
                            <p>Dolore, tempora, incidunt aperiam harum veniam debitis doloribus ab corrupti maiores nihil eum asperiores eveniet, distinctio officia vel at odio sint ex quo voluptatem alias. Asperiores placeat cumque quam sequi.</p>
                            <p>Fugiat iste perferendis corporis voluptatem exercitationem vel deleniti eaque voluptates ipsam placeat. Nulla, sit tempore. Numquam laboriosam eum aliquid aliquam veniam ipsum repudiandae sit quisquam iste, aspernatur doloremque, commodi dolores!</p>
                            <p>Nostrum omnis distinctio aliquam unde esse, laudantium ducimus quia debitis perspiciatis earum. Voluptate a ipsam, minus error maxime repellendus nulla sunt expedita beatae repudiandae architecto officiis ut aperiam fugit sint.</p>
                            <p>Qui, explicabo? Ullam excepturi fugiat quia voluptates, amet animi saepe molestias perspiciatis id unde. Nobis voluptatem laboriosam eveniet praesentium officiis ut expedita. Eligendi ipsa soluta, autem et quod magnam est.</p>
                            <p>Reiciendis consectetur harum rem quidem enim vitae quibusdam. Quia quod tenetur error rerum sint soluta debitis reiciendis dolores. Aut, dignissimos quibusdam deleniti et pariatur dolorum voluptatibus officiis vel nobis nostrum!</p>
                            <p>Tempore totam veniam magni asperiores ipsam quo nisi saepe, minus sapiente. Dolore nam suscipit praesentium alias hic fugit harum adipisci ducimus iusto temporibus obcaecati rerum eius, unde fugiat architecto accusantium!</p>
                            <p>Aut ad veniam quae aliquam sint nobis distinctio, voluptates, dignissimos nostrum excepturi suscipit impedit accusantium eaque fugiat nulla voluptatibus enim, aperiam minima? Temporibus maxime ab tenetur minus deserunt deleniti error!</p>
                            <p>Porro dolores enim sint cupiditate possimus reprehenderit obcaecati corrupti. Consequatur, dolores possimus modi maxime deserunt molestiae nesciunt ut, quia ex numquam dolorum rem, illo ducimus nobis nemo nulla cum fuga.</p>
                            <p>Esse inventore recusandae adipisci quibusdam rem autem, velit harum possimus, quam, illum saepe? Ab deserunt eos eius hic omnis eveniet soluta! Atque commodi consequatur tempore recusandae ex fugiat modi perferendis?</p>
                            <p>Rem tempore mollitia quod quibusdam maiores labore voluptas quisquam itaque delectus fuga provident doloremque sed deserunt dicta deleniti voluptatum eum architecto, quo at. Fugiat, dignissimos reprehenderit aspernatur natus impedit reiciendis.</p>
                            <p>Perspiciatis cumque reiciendis officia a, omnis fugit doloribus quae ea cupiditate facilis quibusdam sed quidem temporibus fugiat ab mollitia molestiae tenetur consectetur itaque odio recusandae sit id! Distinctio, aspernatur soluta?</p>
                            <p>Nobis iusto sequi dignissimos provident, exercitationem dolores, reprehenderit animi debitis aliquam cupiditate tempore voluptas rerum est soluta voluptatem reiciendis harum nam, asperiores ab quo doloribus deserunt sit pariatur quas. Sed.</p>
                            <p>Esse unde consequatur blanditiis nihil autem cupiditate, cumque corporis ipsum ipsa harum nam maxime sunt. Quibusdam pariatur, eos ullam, molestiae rem perspiciatis, minima tempora animi fugit veritatis aliquam quis reiciendis!</p>
                            <p>Excepturi optio voluptate autem quae, accusamus facilis dolore doloribus nostrum natus veritatis asperiores ducimus labore voluptatibus consectetur ipsa ratione fugit dolorum hic et iure ipsam! Ipsum deserunt quisquam voluptatum blanditiis?</p>
                            <p>Odio, sapiente? Voluptatem id iusto eligendi illo cumque provident rem ab repudiandae nostrum? Nisi, totam. Adipisci magnam error, repudiandae ea in quisquam? Vitae deserunt similique fugiat recusandae doloremque dolor doloribus?</p>
                            <p>Odio, qui et quis ab mollitia voluptas cumque perferendis? Quasi fuga necessitatibus modi quia consectetur! Vitae tempora, similique, autem quibusdam ipsa necessitatibus dolorem placeat laborum possimus ratione odit, minima iusto!</p>
                            <p>Rem quisquam unde culpa laudantium dolore! Ratione, magnam cumque quisquam illum quam voluptates, mollitia unde, rerum modi distinctio laudantium id officia explicabo sapiente quasi labore a! Voluptates doloribus placeat maiores.</p>
                            <p>Mollitia minima illo repellendus maiores, reprehenderit obcaecati enim similique amet reiciendis asperiores velit nulla omnis, ipsum magni ipsam ut tempore vero molestiae facilis praesentium a, quidem repellat. Incidunt, quisquam. Aspernatur.</p>
                            <p>Perferendis nam praesentium asperiores repellat dolores! Ipsam omnis quisquam atque, sit quibusdam cum a error tempora voluptates voluptatum excepturi, quaerat ex consequatur nobis iste, laboriosam recusandae eveniet perferendis corporis quam.</p>
                            <p>Esse commodi excepturi assumenda itaque, labore obcaecati blanditiis dolorem! Enim saepe totam possimus eum repudiandae quia pariatur! Pariatur, quaerat? Fugit nam cumque quod, commodi ullam laboriosam ducimus numquam dignissimos placeat?</p>
                            <p>Voluptas qui harum dolores vel animi optio, ipsam officia laborum distinctio sunt, voluptatibus tempora error dicta veritatis commodi perferendis voluptates vero. Beatae, dignissimos. Consectetur, labore reiciendis totam sit repellat amet!</p>
                            <p>Doloribus perferendis quibusdam, consectetur veritatis animi mollitia fuga, ducimus accusamus, voluptatibus molestias voluptatum! Tenetur, aperiam deleniti. Beatae neque eaque, nulla, doloremque esse voluptate quasi libero totam, repudiandae quis fugiat. Deserunt!</p>
                            <p>Quos blanditiis fugit incidunt labore ad velit soluta saepe doloremque neque harum quas assumenda voluptatibus aut facilis, repellat nulla atque dolor nesciunt quae reprehenderit nihil aliquid accusamus suscipit? Magnam, blanditiis?</p>
                            <p>Cupiditate ipsum blanditiis fugit, repellendus recusandae quod consequatur molestiae vero reiciendis, similique aliquam neque in repellat error deserunt debitis tempore aperiam? Aperiam porro doloremque veritatis sed mollitia temporibus ex facilis?</p>
                            <p>Sapiente quae porro architecto aliquam fugiat cum aut incidunt veniam ducimus minus ea, minima esse numquam magnam impedit tempore vero eum dolorem atque consequuntur. Ullam architecto nostrum a distinctio eos!</p>
                            <p>Sit consequatur nisi laboriosam totam fuga dolorem ex repellat! Sunt numquam vero, in soluta voluptatum enim veniam laudantium maxime, dignissimos eum earum eos quod iure atque ut, aliquam recusandae? Sed.</p>
                            <p>Tempore repellat accusamus nihil officiis amet fugit, deleniti sunt! Odit numquam voluptatem optio aliquam veritatis impedit veniam consequatur doloremque, unde quasi recusandae cumque voluptates labore, eveniet delectus quidem maxime hic.</p>
                            <p>Quam maxime ab harum enim ducimus repudiandae tenetur? Tempora, id animi natus quidem perferendis incidunt similique et ex deserunt consequatur adipisci aliquam, culpa assumenda reiciendis aperiam ea officia recusandae possimus?</p>
                            <p>Enim, magni fugiat necessitatibus in et laborum similique accusamus inventore, aspernatur sit ea eligendi alias! In, officiis id vitae adipisci minus hic mollitia, delectus tenetur quis sequi quae quisquam facere!</p>
                            <p>Tempora accusamus quis tempore alias voluptatum, architecto, incidunt iste saepe hic omnis, deleniti dolores soluta debitis laudantium velit. Vitae, molestiae amet. Similique esse, consequatur delectus amet inventore cupiditate dicta velit.</p>
                            <p>Cupiditate ipsum, distinctio tempora labore earum fugit expedita, sapiente voluptatibus, possimus optio doloribus ex explicabo recusandae! Id quidem, sunt accusamus maxime cum nihil mollitia quas. Dolorum culpa cumque animi eveniet!</p>
                            <p>Illo fugiat ipsa alias libero commodi voluptatem nostrum dolor! Pariatur quae laborum, dolores placeat quibusdam velit nesciunt iusto modi vitae dolorem doloremque cumque laboriosam, sint laudantium eveniet accusamus aperiam amet!</p>
                            <p>Optio dignissimos repellat tempora deserunt doloremque consequatur sequi, perferendis eaque consequuntur asperiores similique exercitationem a, id facilis incidunt, ea quasi sed! Distinctio magni expedita praesentium. Inventore blanditiis commodi dolores suscipit?</p>

                        </md-layout-body>
                        
                        <md-navigation-bar .items="${[
                            {id:'0',leading:[{component:'icon',icon:'image'}],label:'Lorem',selected:true},
                            {id:'1',leading:[{component:'icon',icon:'image'}],label:'ipsum'},
                            {id:'2',leading:[{component:'icon',icon:'image'}],label:'dolor'},
                            {id:'3',leading:[{component:'icon',icon:'image'}],label:'sit'},
                        ]}" layout="vertical"></md-navigation-bar>
                        
                    </md-layout>
                </md-layout-border-item>
            </md-layout-border>
        `
    }
}

customElements.define("demo-navigation-bar", DemoNavigationBar);

export default document.createElement("demo-navigation-bar");
