import { html } from "lit";
import { MDComponent } from "../../material/component/component.js";

class DemoTest extends MDComponent {
    render() {
        /* prettier-ignore */
        return html`
            <div class="x-pane x-pane--fit x-pane--sticky">
                <div class="x-pane__header">
                    <div class="x-pane__tool-group">
                        <md-icon class="x-pane__tool">image</md-icon>
                    </div>
                    <div class="x-pane__content">
                        <div class="x-pane__headline">headline</div>
                        <div class="x-pane__subtitle">subtitle</div>
                    </div>
                    <div class="x-pane__tool-group">
                        <md-icon class="x-pane__tool">image</md-icon>
                        <md-icon class="x-pane__tool">image</md-icon>
                        <md-icon class="x-pane__tool">image</md-icon>
                    </div>
                </div>
                <div class="x-pane__body">
                    <div class="x-pane__main">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque delectus esse et qui temporibus autem expedita alias, error ad ab hic tempora dicta vitae praesentium laborum, odit obcaecati asperiores exercitationem?<br><br></p>
                        <p>Ratione quo amet porro nostrum aliquid natus modi nisi quia qui, veritatis corrupti similique. Error optio dolores sunt, repellat recusandae numquam blanditiis rerum assumenda odit, illo aspernatur provident. Laudantium, harum?<br><br></p>
                        <p>Corporis alias ratione consequatur eum dolorem explicabo delectus porro laudantium nisi eveniet doloribus cupiditate voluptas facere, nihil quod quas asperiores veniam pariatur minus iure recusandae aperiam similique. Harum, sunt necessitatibus.<br><br></p>
                        <p>Voluptatem beatae libero neque similique! Minima, iure eum, perferendis quam molestias fugit quos laborum animi sequi eveniet optio dicta dolorem vitae fugiat perspiciatis! Sapiente dignissimos, veniam nostrum molestiae neque accusamus?<br><br></p>
                        <p>Porro ullam, impedit possimus placeat cum, eligendi incidunt optio, deserunt ut nihil accusantium dolorem aut? Iusto, amet ratione, perspiciatis sit exercitationem voluptas qui nulla magnam dolorum aliquid illum minus distinctio.<br><br></p>
                        <p>Debitis nam repudiandae incidunt quaerat ad earum voluptas placeat provident, aliquid fugiat natus nemo? Hic harum dolor laborum aliquam alias labore? Dolores mollitia vitae exercitationem! Veniam iure reiciendis corporis provident?<br><br></p>
                        <p>Temporibus omnis provident error quas optio illum neque quibusdam enim quae. Quas neque, tenetur nisi minus debitis quam facilis commodi nesciunt, cum necessitatibus, earum ab est? Quas nam mollitia beatae!<br><br></p>
                        <p>Beatae earum quos distinctio accusantium ipsa natus voluptatem facere libero totam enim quaerat quae deleniti corrupti aspernatur deserunt minima repudiandae vero a veritatis, nobis vitae error odit. Cupiditate, excepturi debitis?<br><br></p>
                        <p>Sapiente voluptas dolor quos quo impedit vel accusamus, aliquam alias maxime eius iure? Vel similique harum impedit eligendi, magni ea fugit quo vero molestias aut saepe numquam, omnis in sed.<br><br></p>
                        <p>Ex, incidunt nulla officiis dignissimos beatae laboriosam. Vitae tempora, a architecto vel libero commodi reiciendis fuga aliquid cum dolor voluptatibus mollitia voluptatem suscipit nihil soluta, natus eos. Asperiores, vel quis?<br><br></p>
                        <p>Minima ipsum cupiditate quia quos sed earum mollitia rem eligendi, accusamus vel magni odit! Corrupti quam eos aliquid hic, maiores quisquam culpa sit maxime magnam error accusantium fuga doloremque earum.<br><br></p>
                        <p>Corporis, necessitatibus! Rem iusto quibusdam minus temporibus doloribus laborum, repudiandae recusandae! Eos eum, fugiat fugit magni atque amet! Beatae consectetur suscipit eveniet quod blanditiis at cum quia voluptates totam aperiam.<br><br></p>
                        <p>Quia, recusandae nobis consequatur possimus praesentium impedit a illo totam, obcaecati aut laboriosam. Corrupti beatae quod, illum facilis tempora sequi ullam voluptatibus. Cupiditate, iure. Beatae modi officiis ratione assumenda fugit?<br><br></p>
                        <p>Ullam ducimus nisi doloremque tenetur optio in? Obcaecati quae omnis similique impedit architecto alias sunt nesciunt magnam cumque. Nisi ut eius tempora amet eveniet, nostrum in harum sed voluptate fugiat.<br><br></p>
                        <p>Placeat neque magni voluptas id libero, perspiciatis illo sed deleniti laboriosam! Consectetur cum, doloribus, dolores ex numquam ipsam assumenda illum dignissimos nisi ratione hic rerum porro, eos iusto at rem.<br><br></p>
                        <p>Corrupti molestias dolorem consectetur deserunt ducimus voluptates libero qui ad quam, facilis, illum ut beatae eum maiores, omnis atque fugit dicta deleniti necessitatibus ea. Necessitatibus quasi explicabo esse. Aliquam, commodi.<br><br></p>
                        <p>Iste eaque in saepe sequi magni deleniti aspernatur reiciendis non eius accusantium, nemo asperiores delectus, quae voluptatem atque veniam, quos explicabo aperiam quia optio vero illum. Quod suscipit quo magni!<br><br></p>
                        <p>Quo maiores enim molestias eum cum perspiciatis quam excepturi soluta inventore similique ad optio impedit esse repudiandae adipisci saepe consectetur, dolorum rem expedita facilis eveniet reprehenderit. Maxime provident dolores dolorem?<br><br></p>
                        <p>Fugit ipsam veritatis doloremque odio minima quae placeat, assumenda ea? Voluptatem architecto minus dolor, nemo fugiat ut dolorem at praesentium, nam saepe sit accusantium laboriosam fugit ratione excepturi? Quaerat, corrupti!<br><br></p>
                        <p>Eaque ut sed et obcaecati. Repellendus cupiditate quae molestiae officiis ullam eum consequatur iure? Ipsam magnam, maxime nesciunt rem perspiciatis quidem natus voluptatibus earum atque repellat illo iste, cum dicta.<br><br></p>
                        <p>Placeat, vitae architecto. Error, alias. Excepturi nemo illum debitis amet est pariatur maiores nobis iusto vero doloribus distinctio molestiae sit fuga, facilis ipsa, obcaecati dignissimos. Nihil in provident aliquid quos?<br><br></p>
                        <p>Error eos eaque aliquid laudantium alias fuga earum labore veniam doloribus sed ad provident culpa nam dolor voluptas optio, mollitia porro beatae accusamus velit iure iste reiciendis odit? Excepturi, inventore!<br><br></p>
                        <p>Illum autem magnam aut nihil ratione blanditiis et eius quasi odit! Maxime veniam esse quas aliquid facilis numquam sapiente quae eius. Sed exercitationem labore aliquid perferendis dolor tempore autem at.<br><br></p>
                        <p>Debitis placeat voluptate corporis illo vel enim minus eveniet aliquam minima molestiae! Animi repellendus ullam aliquid quibusdam, quo totam a maxime impedit autem neque, quod eos! Veritatis quae voluptatibus libero?<br><br></p>
                        <p>Magnam eligendi itaque quisquam omnis provident id cumque quia porro accusamus earum consequuntur aliquam rem iste eaque enim rerum dolor, repudiandae blanditiis cum, veritatis ad eum. Ex dolore quo architecto.<br><br></p>
                        <p>Mollitia tempore eius repudiandae culpa accusamus cupiditate illo ullam perferendis libero quia. Minus velit sequi odit inventore deserunt, possimus magni quibusdam ab numquam eligendi. Quidem aliquid culpa perferendis voluptatum aliquam?<br><br></p>
                        <p>Nobis, molestiae eum nesciunt beatae tempora aliquam, assumenda sunt culpa, cum soluta in voluptas! Dolorem, porro. Minima commodi quos quia aperiam quibusdam aspernatur ducimus corrupti iusto a ipsam. Perferendis, itaque.<br><br></p>
                        <p>Rem facere fuga quidem deserunt, sint saepe quibusdam commodi, vero officia culpa, ullam eligendi odit veniam corporis. Ea minima illo obcaecati aliquid accusamus, officiis magni eaque non error sit voluptatum!<br><br></p>
                        <p>Provident voluptatem tempore totam ut natus id vel, obcaecati, nobis delectus libero sequi eveniet ullam veniam blanditiis illo deserunt est, pariatur iure? Dolore, officiis delectus id ad distinctio reiciendis sunt?<br><br></p>
                        <p>Harum labore iste minus mollitia consequuntur vero fugiat magni, ullam nobis delectus provident at aliquam autem in tempora reiciendis ipsam praesentium blanditiis ipsum optio facilis nesciunt quibusdam unde nam? In!<br><br></p>
                        <p>Error dicta animi et sapiente? Asperiores soluta similique natus assumenda ipsum eius, suscipit quis libero autem earum, vero possimus totam! Officiis error deleniti consectetur voluptatibus incidunt doloremque! Consectetur, odit reiciendis.<br><br></p>
                        <p>Veniam, amet perferendis reiciendis dolorem magnam voluptatem temporibus facilis, explicabo qui sed perspiciatis similique tenetur? Ipsam earum praesentium sint officia a. Amet explicabo esse ad assumenda impedit obcaecati atque ratione.<br><br></p>
                        <p>At, consequuntur? Commodi eos tempora recusandae voluptatibus, temporibus doloribus fuga magni eum sint velit quasi enim, quos distinctio alias labore tempore corporis. Sunt asperiores laboriosam maiores beatae debitis! Debitis, ipsum.<br><br></p>
                        <p>Exercitationem vel, dolorem rerum similique nulla dolore, mollitia commodi facere aliquam aperiam temporibus qui architecto dolorum reprehenderit voluptatibus pariatur error quam tempora ab veritatis iure perspiciatis quibusdam! Quibusdam, a magnam!<br><br></p>
                        <p>Debitis perspiciatis, eos aut quam magnam provident ipsum aliquam similique saepe ratione perferendis itaque libero dolorum sequi suscipit id, nesciunt placeat totam autem corporis mollitia quasi a voluptatem nisi! Aspernatur.<br><br></p>
                        <p>Consectetur hic explicabo suscipit odio, deserunt animi molestias minus corrupti! Tenetur velit sit distinctio illum, eveniet facilis asperiores dolorem dicta eligendi! Alias modi eaque voluptate eos adipisci. Ducimus, accusamus at.<br><br></p>
                        <p>Iusto sunt sint voluptatum, ad beatae deleniti eaque, doloribus ipsum minima dolorem perferendis unde! Qui quae cumque quasi repellat deserunt magnam nostrum accusamus sequi, tempora blanditiis quia eaque voluptate sint?<br><br></p>
                        <p>Consectetur dolores perspiciatis aliquam laborum eos, maiores explicabo quo molestias ad dolorum rem voluptatum dolore, numquam, consequatur et blanditiis sit illo? Quisquam fuga quasi ipsa provident culpa magnam velit consequuntur.<br><br></p>
                        <p>Error maxime itaque delectus magni perspiciatis ratione beatae asperiores dolor, quasi necessitatibus voluptas. Quo in odit doloribus iusto debitis minima nisi, itaque adipisci! Tempore voluptatum hic perspiciatis sit odio dolor?<br><br></p>
                        <p>Atque, cupiditate repellat assumenda sapiente aliquam culpa vitae nisi saepe dolore dicta et, aperiam architecto, sit quo magnam quidem voluptate nesciunt modi asperiores magni consequatur qui facilis in! Itaque, ea!<br><br></p>
                        <p>Esse nemo praesentium quas sequi laboriosam officia iusto, eaque nesciunt reprehenderit autem porro. Quos tenetur quae omnis excepturi facere est laborum sint, dolores debitis, vitae quidem quis voluptatem animi pariatur!<br><br></p>
                        <p>Ipsa et odit iste omnis id. Pariatur similique nemo enim quis vitae, iste incidunt quia distinctio, suscipit provident numquam nulla aut animi odit excepturi ad soluta, magnam iusto sed molestiae?<br><br></p>
                        <p>Ipsum corporis magni reiciendis recusandae maiores doloribus dolorem nisi perferendis excepturi amet, cumque nostrum mollitia natus quis accusantium optio, animi nemo. Dicta saepe laboriosam, eum vero illo voluptas tenetur cumque!<br><br></p>
                        <p>Adipisci sint ut totam, pariatur tempore itaque atque saepe voluptatibus hic veniam ratione corporis expedita eos inventore dolorem impedit amet! Ducimus enim adipisci assumenda natus similique possimus non voluptas ipsam!<br><br></p>
                        <p>Aspernatur voluptates quis aperiam animi quam nesciunt consequatur maxime magni repellat eos, tenetur fugit in assumenda maiores vel quibusdam itaque iusto labore tempora! Voluptas corporis aut delectus, voluptatum inventore commodi.<br><br></p>
                        <p>Aspernatur quidem, distinctio neque voluptatem corrupti, nam et error, exercitationem reprehenderit quaerat repudiandae veritatis maxime facilis iste beatae eum minus consequatur minima delectus earum impedit ut animi vero! Corporis, quisquam.<br><br></p>
                        <p>Tempore a iste perspiciatis nisi praesentium eveniet. Aut neque, necessitatibus excepturi voluptatum explicabo recusandae culpa. Explicabo alias, iste atque, natus cumque sequi hic obcaecati doloremque, ipsum temporibus ipsa reprehenderit sunt!<br><br></p>
                        <p>Fugiat consequuntur reiciendis magnam quas voluptas, sunt minus perferendis quibusdam soluta similique debitis expedita eveniet error et eos itaque enim porro quaerat est hic. Quis accusantium quam eius repellat. Illo.<br><br></p>
                        <p>Laboriosam quisquam facere cupiditate nulla nihil consequuntur quasi tenetur, omnis iusto! At, architecto amet mollitia non repellendus alias earum incidunt modi, a sint ad id quibusdam tenetur molestias quas necessitatibus?<br><br></p>
                        <p>Unde officia iste repellendus? Est et qui repudiandae tenetur error, nobis minima unde dicta temporibus, perferendis corporis recusandae nemo reprehenderit fugiat, vero praesentium quisquam libero dolore consequuntur. Nobis, ad iure?<br><br></p>
                        <p>Nemo corrupti numquam eaque provident deleniti dolores quod quia nobis vitae repellendus! Iste, dolores. Quo facilis numquam excepturi, sed soluta tempore, cupiditate eos recusandae maiores molestias, commodi reiciendis quis odit.<br><br></p>
                        <p>Aliquid temporibus, minus omnis cupiditate perspiciatis qui, quo odit autem dignissimos dolore itaque voluptatum, enim pariatur dicta sint illum quidem. Ea hic laborum eligendi similique molestiae a quidem totam mollitia.<br><br></p>
                        <p>Culpa quidem est iste. Eius sapiente sint, corrupti quibusdam quae beatae doloremque ut odio deserunt quisquam atque officiis iusto nesciunt doloribus, aliquam quia fugiat illo ab vitae. Id, explicabo quam!<br><br></p>
                        <p>Minima cumque corrupti maiores at laboriosam aperiam, exercitationem, consectetur quibusdam impedit hic, recusandae debitis vel enim non dolores dignissimos commodi culpa voluptate earum iure corporis. At possimus tenetur ipsa quasi.<br><br></p>
                        <p>Quasi, nobis non? Praesentium laudantium magnam hic quam, perspiciatis earum repudiandae ratione, accusantium sed nostrum maiores. Sint, tenetur temporibus, nulla ex odit voluptate nam obcaecati, a facere ipsum ad amet!<br><br></p>
                        <p>Alias quidem repellendus ea, optio autem molestias eaque aliquid repellat iure enim expedita earum eius illo at ex assumenda facere unde quos, saepe quam, iste dolorem! Ad quo enim ipsa!<br><br></p>
                        <p>A eaque suscipit numquam reprehenderit sed inventore eligendi, ipsa officiis deleniti reiciendis sapiente pariatur nihil voluptatum voluptates eveniet ea voluptas fugit! Fugiat inventore dolorem quam! Nisi officiis odit alias consectetur?<br><br></p>
                        <p>Inventore nobis corporis veritatis doloribus cum numquam optio odit facilis earum aut veniam ducimus magnam placeat repellat, at ipsum, possimus quidem ut amet quas eaque? Nobis ad atque reprehenderit necessitatibus!<br><br></p>
                        <p>Illum nemo blanditiis, placeat odio nulla commodi unde aliquid libero iusto atque veritatis laboriosam tempora dicta explicabo, soluta sit? Eius culpa ducimus voluptates cumque at! Odit culpa minima deleniti corrupti!<br><br></p>
                        <p>Nam officia, corporis, delectus asperiores blanditiis ex maiores, qui quas quisquam hic corrupti unde ducimus libero esse ipsum velit incidunt aspernatur enim minima. Quaerat enim eum dolorum, aspernatur similique quam?<br><br></p>
                        <p>Consequatur eius deserunt, dolores vitae aliquam totam quisquam incidunt. Minima vero cumque perferendis, commodi optio maxime voluptatibus in ducimus nihil quia fugiat aut, iure temporibus sint beatae! Laudantium, totam voluptates?<br><br></p>
                        <p>Ipsa aperiam dolor voluptate ducimus atque voluptatem cupiditate, alias nostrum, inventore eaque sint est autem sit molestias a repellendus reprehenderit suscipit voluptatum corrupti ipsam officia numquam molestiae! Vel, dolorum dicta.<br><br></p>
                        <p>Veritatis voluptatum tempora rem eos, id veniam aspernatur mollitia laudantium illo totam exercitationem possimus sapiente animi illum, culpa distinctio minima porro a, sed laboriosam. Veniam saepe nihil repellendus nobis quibusdam.<br><br></p>
                        <p>Magni libero nulla molestiae ratione molestias, dolore reiciendis repudiandae! Nihil a et, dolore voluptatibus suscipit mollitia sunt perspiciatis ad ab veritatis eius architecto blanditiis voluptas dolor quam, recusandae illo earum.<br><br></p>
                        <p>Cumque libero sunt ducimus, alias nulla nesciunt cum officiis vel non! Temporibus et in tempore eos beatae, porro hic maiores tempora dolores illo. Quae consectetur provident voluptatum in et dolorum.<br><br></p>
                        <p>Impedit excepturi nisi, eos provident ipsam voluptatibus nulla libero sunt dignissimos quaerat quidem accusamus nihil error soluta molestias. Asperiores iure saepe libero est quis eveniet quasi magnam similique obcaecati officiis.<br><br></p>
                        <p>Magni nostrum, eum et minima deleniti provident similique minus fugit quidem. Cum, atque laudantium, repellat tempora a voluptates similique necessitatibus hic aut quam quaerat voluptas distinctio alias sed, voluptatibus obcaecati.<br><br></p>
                        <p>Eos ut quam error aut minus mollitia eveniet inventore eaque iusto aliquam modi obcaecati labore, totam quis? Atque doloremque consectetur voluptates facilis iste vel alias tempora enim, eum laudantium consequatur!<br><br></p>
                        <p>Modi magnam perferendis temporibus saepe debitis ut autem vel qui magni animi. Accusantium eligendi veritatis nulla eveniet corrupti odit magni, esse aut doloremque ut, quia voluptate praesentium commodi provident quidem.<br><br></p>
                        <p>Maiores eaque enim ad voluptatem, repellat magni totam maxime? Vel atque voluptatum fuga commodi dolorum velit nam iste modi aut, similique nihil. Consectetur, voluptatem. Quisquam vero voluptatibus temporibus cumque unde?<br><br></p>
                        <p>Voluptates, error labore quas odit velit repellat aliquid fugit ipsa architecto, amet eum. Laborum, deleniti. Eos inventore necessitatibus placeat voluptatem molestias magni, nesciunt autem? Minus error quaerat iste repudiandae voluptate?<br><br></p>
                        <p>Praesentium itaque sint cum quos magnam ut sed, labore delectus autem asperiores, exercitationem cupiditate aliquam perspiciatis possimus quis dolore similique aliquid? Ut alias, modi consectetur ullam rerum quod sint incidunt?<br><br></p>
                        <p>Vitae veniam debitis cum expedita ut similique cumque atque, fuga molestias explicabo fugit sed accusamus praesentium maxime voluptatem nesciunt. Totam est facilis alias atque neque vero veritatis illum necessitatibus esse!<br><br></p>
                        <p>Id odit distinctio pariatur debitis sint laudantium numquam saepe ut facilis nobis, aliquid non velit fugit, voluptatum nemo. Error, quis alias saepe ut assumenda ad accusantium dicta beatae perspiciatis quam.<br><br></p>
                        <p>Fuga fugiat, ullam quo rerum, maxime impedit corrupti cumque corporis nobis voluptatibus necessitatibus, exercitationem explicabo? Corrupti obcaecati, temporibus doloribus delectus inventore eligendi voluptatem tempore nisi aliquam deleniti. Perspiciatis, mollitia fuga.<br><br></p>
                        <p>Voluptatem tenetur voluptas quaerat odit sunt voluptate quae, eveniet molestiae quam doloremque explicabo accusamus harum dolores, odio quod? Et non ex quo iure harum. Iusto quasi a nam incidunt minus.<br><br></p>
                        <p>Delectus, repudiandae sunt? Sit dicta mollitia nam reiciendis adipisci unde repudiandae, vel ea. Dolore et beatae optio, aspernatur ea quaerat, enim consequatur accusantium molestiae modi nobis. Nisi eaque vero magnam.<br><br></p>
                        <p>Illum soluta consectetur laboriosam eaque tempora aperiam voluptatibus molestiae mollitia doloribus veniam blanditiis deserunt repellendus, pariatur at accusantium, nam quaerat voluptatem. Blanditiis consequuntur, rem repellendus recusandae in ipsum omnis fugit.<br><br></p>
                        <p>Voluptate, ratione itaque? Earum, doloremque! Illo fugiat vel ratione dolore dicta, ipsa distinctio velit odit facere aspernatur alias vero porro iusto consectetur laboriosam nemo expedita ipsum omnis? Ducimus, nostrum eaque!<br><br></p>
                        <p>Quia laudantium delectus soluta corrupti vero, itaque eligendi dignissimos assumenda hic consequuntur ad exercitationem sunt excepturi ipsum pariatur suscipit unde deleniti nisi magni ducimus officia distinctio dolorum non dolore? Architecto.<br><br></p>
                        <p>Suscipit, nulla sunt dolor ut quibusdam beatae perspiciatis consequuntur placeat illum explicabo id omnis iure dolorem. Perferendis placeat vero itaque, non molestiae possimus facere et ipsum delectus, libero quis assumenda?<br><br></p>
                        <p>Dolorum ad autem dolor id expedita commodi dignissimos quaerat blanditiis, magni animi, dolore eligendi consequuntur esse iste suscipit sed deleniti architecto neque amet asperiores error molestiae. Voluptatibus repellat voluptas accusamus.<br><br></p>
                        <p>Fugit, est et. Repellat incidunt qui, dicta ex nesciunt numquam aut illo aperiam dolores praesentium vero libero veniam obcaecati amet sapiente accusantium hic iusto est rerum beatae? Ducimus, tempore consequuntur.<br><br></p>
                        <p>Et similique nam distinctio maiores dicta, id beatae neque delectus, excepturi nesciunt vel. Inventore, blanditiis eveniet, fuga vitae natus voluptatem sunt esse officia tempora nemo quos! Et est sapiente ab.<br><br></p>
                        <p>Aperiam eveniet delectus nisi. Odit quo quod laudantium cupiditate iure cum et? Ipsam repudiandae laborum nulla quod reiciendis. Non odio iusto nostrum vitae blanditiis quidem deserunt exercitationem, molestiae hic pariatur?<br><br></p>
                        <p>Itaque, ipsam unde doloribus error voluptatibus sint dolores placeat nisi labore officiis reprehenderit et iste ratione enim blanditiis quasi, ipsum magni sunt voluptates eius amet assumenda ab eum! Eveniet, esse.<br><br></p>
                        <p>Consequuntur eveniet atque quidem itaque, asperiores a? Pariatur vitae temporibus fuga placeat minus repudiandae tempora! Voluptates, provident. Quas itaque odio, exercitationem, sed illum dignissimos placeat possimus asperiores dolorum iure molestias?<br><br></p>
                        <p>Beatae, odit! Accusantium officiis saepe tenetur dicta sed ex cupiditate magni placeat, omnis voluptas. Obcaecati, fuga? Repellat nam numquam saepe a, porro adipisci laboriosam laudantium atque rerum aliquid modi ab.<br><br></p>
                        <p>Distinctio nesciunt, explicabo eligendi mollitia cum corporis suscipit qui obcaecati illum nemo dolore quo magnam eaque, praesentium officia aliquid itaque placeat! Voluptates magnam, iusto error quidem eaque obcaecati quo repellat?<br><br></p>
                        <p>Provident porro, consequatur voluptate quibusdam libero, deserunt esse totam quos sequi minima reprehenderit! Itaque, consequuntur facere quidem id modi similique quo in animi impedit atque. Enim quibusdam doloremque nobis minus.<br><br></p>
                        <p>Laborum beatae nam cupiditate accusamus necessitatibus natus earum. Aspernatur assumenda necessitatibus, quis nesciunt enim tempore, veniam numquam sint eaque tempora esse consectetur, illo magnam est. Veniam earum quia labore dolorum!<br><br></p>
                        <p>Animi enim saepe quaerat tempore laboriosam in neque reprehenderit id tenetur omnis, adipisci debitis odit veritatis itaque, voluptatem aspernatur fugiat laudantium, error quisquam inventore! Labore distinctio ratione necessitatibus error provident.<br><br></p>
                        <p>Optio qui error praesentium sit voluptatibus est neque animi fugiat voluptate commodi impedit excepturi debitis ipsum, magnam architecto alias ea velit tempora temporibus harum tempore deleniti quidem perferendis ipsa. Earum?<br><br></p>
                        <p>Consectetur nisi possimus inventore perspiciatis provident eius voluptates nesciunt accusantium, a eligendi asperiores fugiat repellat recusandae impedit expedita consequatur maxime, quas dignissimos dicta voluptate cumque? Quaerat voluptatibus quis veritatis obcaecati.<br><br></p>
                        <p>Unde tempore aut quaerat fugit cumque eaque minus labore laboriosam voluptates quis blanditiis accusantium architecto fugiat consequuntur doloribus, corporis maiores nam est perferendis sit vel! Ipsa laboriosam maiores facilis repudiandae!<br><br></p>
                        <p>A voluptate suscipit delectus fugiat saepe facere et nostrum blanditiis! Iusto quae iste tempora cumque beatae alias quis magni repellendus tempore ipsa. Facere pariatur illum cumque numquam nesciunt error natus.<br><br></p>
                        <p>Molestiae iste dolor aspernatur tempora! Molestias beatae maiores, soluta adipisci quo minima libero! Distinctio sed quibusdam amet nisi! Beatae, itaque! Cum omnis necessitatibus itaque hic, minus quibusdam aliquid optio ea?<br><br></p>
                        <p>Cumque fugit ducimus, adipisci hic aliquam cupiditate vero ullam magnam aspernatur laborum pariatur atque, quod doloremque quos. Assumenda repellendus animi atque sapiente reprehenderit incidunt at. Animi voluptate impedit non delectus.<br><br></p>
                        <p>Quisquam rerum officiis numquam! Et, dolorum eos sit totam, saepe laborum est, sunt ratione magni qui adipisci neque maxime incidunt. Fugiat rerum quisquam architecto, eveniet non nostrum possimus perspiciatis ut.<br><br></p>
                        <p>Natus voluptatum laudantium maxime quos, porro, exercitationem eaque consectetur, voluptates beatae recusandae sequi quidem molestiae. Amet quam distinctio iure recusandae provident id voluptatem ratione ab, architecto, placeat minima saepe eligendi!<br><br></p>
                    </div>
                    <div class="x-pane__footer">
                        <md-button class="x-pane__button" label="button"></md-button>
                        <md-button class="x-pane__button" label="button"></md-button>
                    </div>
                </div>
            </div>
        `
    }
}

customElements.define("demo-test", DemoTest);

export default document.createElement("demo-test");
